FROM node:18.20.7-alpine3.21 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

FROM node:18.20.7-alpine3.21

WORKDIR /app

COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/build /app/build

EXPOSE 4000

CMD [ "npm", "run", "start" ]